# Use root/example as user/password credentials
version: '3.1'

services:

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
        - "3000:3000"

  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
        - "5000:5000"
    depends_on:
      - mongo
    environment:
      MONGO_URL: mongodb://root:example@mongo:27017/
      MONGO_DB_NAME: mydb

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
        - "27017:27017"

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH: false
