name: Mirror Repository

on:
  push:
    branches:
        - main


jobs:
  Push:
    runs-on: ubuntu-latest
    if: github.repository == 'EpitechNAN-MSC2027/WhatsUp'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Mirror to Epitech repository
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            git@github.com:EpitechMscProPromo2027/T-JSF-600-NAN_10.git
          ssh_private_key:
              ${{ secrets.SSH_SECRET }}
